addons: addressvirtual: enslave macvlan to vrf before running ops (ie. add addr etc.)
if a macvlan needs to be enslaved to a VRF we should do it right after it's creation.
This patch is moving the enslavement code to the right place before  we start changing
the macvlan hwaddress and adding ip addresses.

Ticket: CM-20240
Reviewed By: Roopa
Testing Done:

[13:54:29] root:~ # ip addr show
1: lo: <LOOPBACK> mtu 65536 qdisc noqueue state DOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:80:e2:97 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe80:e297/64 scope link
       valid_lft forever preferred_lft forever
3: swp1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
4: swp2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
5: swp3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 08:00:27:bc:04:3c brd ff:ff:ff:ff:ff:ff
6: swp4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 08:00:27:2b:3b:b6 brd ff:ff:ff:ff:ff:ff
7: swp5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 08:00:27:27:f4:14 brd ff:ff:ff:ff:ff:ff
8: swp6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
9: swp7: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 08:00:27:4a:77:20 brd ff:ff:ff:ff:ff:ff
[13:54:31] root:~ # cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto bridge
iface bridge
	bridge-vlan-aware yes
	bridge-ports swp1
	bridge-vids 4011 4012 4021 4022 1900 1901 1902 1903
	hwaddress a8:2b:b5:b5:44:16
	bridge-stp off

auto vlan1901
iface vlan1901
	alias LAB-CUST-VMS
	vlan-id 1901
	vlan-raw-device bridge
	address 2a06:c01:1:1901::2/64
	address 185.98.121.2/24
	address-virtual 00:00:5e:00:01:a1 2a06:c01:1:1901::1/64 fe80::1/64 185.98.121.1/24
	vrf public
	#up ip link set dev vlan1901-v0 addrgenmode none
	#up ip link set dev vlan1901-v0 down
	#up ip link set dev vlan1901-v0 up
	#up ip address add fe80::1/64 dev vlan1901-v0

auto public
iface public
	address 2a01:6640:bb::11/128
	address 5.102.144.11/32
	vrf-table auto

[13:54:44] root:~ #
[13:54:45] root:~ #
[13:54:45] root:~ # ifreload -a -v &> ifreload.commented_cmds.log
[13:54:56] root:~ # ip addr show vlan1901-v0
53: vlan1901-v0@vlan1901: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master public state UP group default
    link/ether 00:00:5e:00:01:a1 brd ff:ff:ff:ff:ff:ff
    inet 185.98.121.1/24 scope global vlan1901-v0
       valid_lft forever preferred_lft forever
    inet6 2a06:c01:1:1901::1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link
       valid_lft forever preferred_lft forever
    inet6 fe80::200:5eff:fe00:1a1/64 scope link
       valid_lft forever preferred_lft forever
[13:54:59] root:~ # cat ifreload.commented_cmds.log |& grep f80
[13:55:12] root:~ # cat ifreload.commented_cmds.log |& grep fe80
addr add fe80::1/64 dev vlan1901-v0
[13:55:18] root:~ #
[13:55:43] root:~ #
[13:55:43] root:~ #
[13:55:53] root:~ #
[13:55:53] root:~ #
[13:55:53] root:~ #
[13:55:53] root:~ # cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto bridge
iface bridge
	bridge-vlan-aware yes
	bridge-ports swp1
	bridge-vids 4011 4012 4021 4022 1900 1901 1902 1903
	hwaddress a8:2b:b5:b5:44:16
	bridge-stp off

auto vlan1901
iface vlan1901
	alias LAB-CUST-VMS
	vlan-id 1901
	vlan-raw-device bridge
	address 2a06:c01:1:1901::2/64
	address 185.98.121.2/24
	address-virtual 00:00:5e:00:01:a1 2a06:c01:1:1901::1/64 fe80::1/64 185.98.121.1/24
	vrf public
	up ip link set dev vlan1901-v0 addrgenmode none
	up ip link set dev vlan1901-v0 down
	up ip link set dev vlan1901-v0 up
	up ip address add fe80::1/64 dev vlan1901-v0

auto public
iface public
	address 2a01:6640:bb::11/128
	address 5.102.144.11/32
	vrf-table auto

[13:55:56] root:~ #
[13:55:56] root:~ #
[13:55:56] root:~ # ifdown -a -X eth0
[13:55:58] root:~ # ifdown -a -X eth0
error: no ifaces found matching given allow lists (or interfaces were probably never up ?)
[13:55:59] root:~ # ifreload -a -v &> ifreload.up_cmds.log
[13:56:05] root:~ #
[13:56:07] root:~ # ip addr show vlan1901-v0
57: vlan1901-v0@vlan1901: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master public state UP group default
    link/ether 00:00:5e:00:01:a1 brd ff:ff:ff:ff:ff:ff
    inet 185.98.121.1/24 scope global vlan1901-v0
       valid_lft forever preferred_lft forever
    inet6 2a06:c01:1:1901::1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link
       valid_lft forever preferred_lft forever
[13:56:08] root:~ #
[13:56:11] root:~ #
[13:56:11] root:~ # cat ifreload.up_cmds.log |& grep fe80
addr add fe80::1/64 dev vlan1901-v0
info: executing ip address add fe80::1/64 dev vlan1901-v0
[13:56:21] root:~ #

Signed-off-by: Julien Fortin <julien@cumulusnetworks.com>