--allow option: add support for interface list
Ticket: CM-16818
Reviewed By: Roopa
Testing Done:

[13:09:30] root:~ # cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

allow-hotplug vx42
iface vx42
      vxlan-id 42

allow-hotplug2 bond0
iface bond0
      bond-slaves swp2

auto usb0
iface usb0
      vxlan-id 84

auto br0
iface br0
      bridge-ports swp7

[13:09:32] root:~ #
[13:09:32] root:~ #
[13:09:33] root:~ # ifquery -a
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto usb0
iface usb0
	vxlan-id 84

auto br0
iface br0
	bridge-ports swp7

[13:09:38] root:~ #
[13:09:39] root:~ #
[13:09:39] root:~ #  ifquery --allow hotplug
iface vx42
	vxlan-id 42

[13:09:43] root:~ #  ifquery --allow hotplug2
iface bond0
	bond-slaves swp2

[13:09:47] root:~ # ifquery --allow hotplug2 --allow hotplug
iface vx42
	vxlan-id 42

iface bond0
	bond-slaves swp2

[13:09:56] root:~ #
[13:10:01] root:~ #
[13:10:01] root:~ # ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:80:e2:97 brd ff:ff:ff:ff:ff:ff
3: swp1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
4: swp2: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
5: swp3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:bc:04:3c brd ff:ff:ff:ff:ff:ff
6: swp4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:2b:3b:b6 brd ff:ff:ff:ff:ff:ff
7: swp5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:27:f4:14 brd ff:ff:ff:ff:ff:ff
8: swp6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
9: swp7: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:4a:77:20 brd ff:ff:ff:ff:ff:ff
[13:10:03] root:~ #
[13:10:03] root:~ #
[13:10:03] root:~ #
[13:10:09] root:~ # ifup --allow=hotplug usb0 -d
...
debug: scheduling '['pre-up', 'up', 'post-up']' for ['vx42', 'usb0']
debug: dependency graph {
	vx42 : []
	usb0 : []
	swp2 : []
	swp7 : []
}
...
[13:10:28] root:~ #
[13:10:28] root:~ #
[13:10:28] root:~ #
[13:10:28] root:~ # ifquery -a -c
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp                                                [pass]

auto usb0
iface usb0                                                          [pass]
	vxlan-id 84                                                 [pass]

auto br0
iface br0                                                           [fail]

[13:10:32] root:~ # ifquery --allow hotplug2 --allow hotplug -c
iface vx42                                                          [pass]
	vxlan-id 42                                                 [pass]

iface bond0                                                         [fail]

[13:10:39] root:~ # ifquery --allow hotplug usb0 -c
iface vx42                                                          [pass]
	vxlan-id 42                                                 [pass]

auto usb0
iface usb0                                                          [pass]
	vxlan-id 84                                                 [pass]

[13:10:45] root:~ #
[13:10:50] root:~ #
[13:10:51] root:~ #
[13:10:51] root:~ # ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:80:e2:97 brd ff:ff:ff:ff:ff:ff
3: swp1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
4: swp2: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
5: swp3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:bc:04:3c brd ff:ff:ff:ff:ff:ff
6: swp4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:2b:3b:b6 brd ff:ff:ff:ff:ff:ff
7: swp5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:27:f4:14 brd ff:ff:ff:ff:ff:ff
8: swp6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
9: swp7: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:4a:77:20 brd ff:ff:ff:ff:ff:ff
21: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 0a:d6:b8:2b:55:2f brd ff:ff:ff:ff:ff:ff
22: vx42: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether fe:eb:35:5f:86:52 brd ff:ff:ff:ff:ff:ff
[13:10:52] root:~ #
[13:10:53] root:~ #
[13:10:53] root:~ #
[13:10:53] root:~ #
[13:10:53] root:~ # ifdown --allow hotplug -d
...
debug: scheduling '['pre-down', 'down', 'post-down']' for ['vx42']
debug: dependency graph {
	vx42 : []
}
[13:10:59] root:~ #
[13:11:00] root:~ #
[13:11:00] root:~ #
[13:11:00] root:~ #
[13:11:01] root:~ # ifquery --allow hotplug usb0 -c
iface vx42                                                          [fail]

auto usb0
iface usb0                                                          [pass]
	vxlan-id 84                                                 [pass]

[13:11:11] root:~ #
[13:11:14] root:~ #
[13:11:14] root:~ # ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:80:e2:97 brd ff:ff:ff:ff:ff:ff
3: swp1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
4: swp2: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
5: swp3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:bc:04:3c brd ff:ff:ff:ff:ff:ff
6: swp4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:2b:3b:b6 brd ff:ff:ff:ff:ff:ff
7: swp5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:27:f4:14 brd ff:ff:ff:ff:ff:ff
8: swp6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
9: swp7: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:4a:77:20 brd ff:ff:ff:ff:ff:ff
21: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 0a:d6:b8:2b:55:2f brd ff:ff:ff:ff:ff:ff
[13:11:16] root:~ #
[13:11:20] root:~ #
[13:11:21] root:~ # ifreload -a
[13:11:21] root:~ # ifquery -a -c
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp                                                [pass]

auto usb0
iface usb0                                                          [pass]
	vxlan-id 84                                                 [pass]

auto br0
iface br0                                                           [pass]
	bridge-ports swp7                                           [pass]

[13:11:25] root:~ # ifquery --allow hotplug2 --allow hotplug -c
iface vx42                                                          [fail]

iface bond0                                                         [fail]

[13:11:32] root:~ #
[13:11:38] root:~ #
[13:11:38] root:~ #
[13:11:38] root:~ # ifdown --allow hotplug -d
error: no ifaces found matching given allow lists (or interfaces were probably never up ?)
[13:11:40] root:~ #
[13:12:15] root:~ # ip link show vx42
Device "vx42" does not exist.
[13:12:19] root:~ # ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:80:e2:97 brd ff:ff:ff:ff:ff:ff
3: swp1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
4: swp2: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
5: swp3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:bc:04:3c brd ff:ff:ff:ff:ff:ff
6: swp4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:2b:3b:b6 brd ff:ff:ff:ff:ff:ff
7: swp5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:27:f4:14 brd ff:ff:ff:ff:ff:ff
8: swp6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:c5:38:ed brd ff:ff:ff:ff:ff:ff
9: swp7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master br0 state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:4a:77:20 brd ff:ff:ff:ff:ff:ff
21: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 0a:d6:b8:2b:55:2f brd ff:ff:ff:ff:ff:ff
23: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 08:00:27:4a:77:20 brd ff:ff:ff:ff:ff:ff
[13:12:22] root:~ #
[13:13:16] root:~ #
[13:13:45] root:~ #
[13:13:45] root:~ # ifdown -a -X eth0  -d
...
debug: scheduling '['pre-down', 'down', 'post-down']' for ['lo', 'usb0', 'br0']
debug: dependency graph {
	lo : []
	usb0 : []
	br0 : ['swp7']
	swp7 : []
}
...
[13:13:46] root:~ #

Signed-off-by: Julien Fortin <julien@cumulusnetworks.com>