ifupdown2: bridge: try to interpret bridge port add rtnetlink return strings from iproute and print meaningful error
Ticket: CM-6278
Reviewed By: CCR-3851
Testing Done: Tested error cases for bridge with multiple vlans when
net.bridge.bridge-allow-multiple-vlans is zero

new error message with the patch:

$ifquery br-vlan0502
auto br-vlan0502
iface br-vlan0502
    bridge-ports swp2.502 swp3.12
    bridge-stp on
    mstpctl-portadminedge swp2.502=yes
    mstpctl-portbpdufilter swp2.502=yes
    address 3.50.2.1/24

$ifup br-vlan0502

<snip>
error: br-vlan0502: net.bridge.bridge-allow-multiple-vlans not set, multiple
vlans not allowed
error: br-vlan0502: failed to execute cmd 'ip -force -batch - [link set
dev swp3.12 master br-vlan0502
addr flush dev swp3.12
]'(RTNETLINK answers: Invalid argument
Command failed -:1)

(cherry picked from commit 3d06230cba47e8d8244439ea4d07dbdf05011067)