addons: bridge: warn/err if bridge-access is missing under vxlan bridge VA port
Ticket: CM-14209
Reviewed By: Roopa
Testing Done:

$ cat /etc/network/interfaces
auto vxlan1000
iface vxlan1000
       vxlan-id 1000
       vxlan-local-tunnelip 172.16.20.103
       vxlan-remoteip 172.16.20.106

auto bridge
iface bridge
       bridge-vlan-aware yes
       bridge-ports swp1 vxlan1000
       bridge-vids 100 200

$
$ ifdown -a -X eth0
$ ifreload -a -s
warning: vxlan1000: `bridge-access` attribute is mandatory when vxlan device (vxlan1000) is part of vlan aware bridge (bridge)
$ ifreload -a
warning: bridge: `bridge-access` attribute is mandatory when vxlan device (vxlan1000) is part of vlan aware bridge (bridge)
error: bridge: errors applying port settings
$ ifreload -a
error: vxlan1000: `bridge-access` attribute is mandatory when vxlan device (vxlan1000) is part of vlan aware bridge (bridge)
warning: bridge: `bridge-access` attribute is mandatory when vxlan device (vxlan1000) is part of vlan aware bridge (bridge)
error: bridge: errors applying port settings
$

Signed-off-by: Julien Fortin <julien@cumulusnetworks.com>