bondutils: get_slaves: should return an empty list instead of None
Ticket: 0
Reviewed By: Roopa, Nikhil
Testing Done:

$ ifdown -a -X eth0
$ ifquery bond0
auto bond0
iface bond0
        bond-slaves swp424242

$ ifup -a
error: bond0: skipping slave swp424242, does not exist
$ ifquery bond0 -c
error: argument of type 'NoneType' is not iterable
auto bond0
iface bond0

$

with patch:

$ ifquery -c bond0
auto bond0
iface bond0                                                         [fail]
        bond-slaves None                                            [fail]

$

Signed-off-by: Julien Fortin <julien@cumulusnetworks.com>