Pytest: add initial support for pytest with code coverage
tests/: pytest related files and tests, test are converted from the ifupdown2-qa repo
__main__: necessary path injection (can probably be removed or adjusted in the future)

test_l2.py for l2 tests
test_l3.py for l3 tests
test_coverage.py for code coverage and static analysis (flake8, mypy but disabled at the moment due to the huge amount of errors)

Usage:

$ export PYTEST_REMOTE_HOST=$DEV;
$ export PYTEST_REMOTE_USER=$USER;
$ export PYTEST_REMOTE_PASSWORD=$PW
$ pytest
=== short test summary info ===
FAILED tests/test_coverage.py::test_coverage - AssertionError: Coverage less than 75% - total coverage: 54.5492335671603 - details in ./tests/results/coverage_data.tar.gz
=== 1 failed, 24 passed, 2 skipped, 9 warnings in 333.02s (0:05:33) ===

We can lower the coverage threshold until we had more test or clean up the dead code in ifupdown2
Right now all test run with coverage enabled on, and it's not possible to disable it, that will come in a different MR.

Signed-off-by: Julien Fortin <jfortin@nvidia.com>