addons: bridge: fix hashmax and hashel upstream default in modinfo dict
Ticket: 0
Reviewed By: Roopa, Nikhil G
Testing Done:

This is the behavior that I can see on debian 9.1 (kernel 4.9), debian8 (kernel 3.16), ubuntu 16 (kernel 4.4):

$ ip link add dev br1 type bridge
$ cat /sys/class/net/br1/bridge/hash_max
512
$ cat /sys/class/net/br1/bridge/hash_elasticity
4
$

but in ifupdown2 we advertise 4096 default (in bridge module modinfo dict)

'bridge-hashel' :
    { 'help' : 'set hash elasticity',
      'validrange' : ['0', '4096'],
      'default' : '4096',
      'example' : ['bridge-hashel 4096']},
'bridge-hashmax' :
    { 'help' : 'set hash max',
      'validrange' : ['0', '4096'],
      'default' : '4096',
      'example' : ['bridge-hashmax 4096']},

but these are Cumulus default:

➜  ~ ip link add dev br1 type bridge
➜  ~ cat /sys/class/net/br1/bridge/hash_max
4096
➜  ~ cat /sys/class/net/br1/bridge/hash_elasticity
4096
➜  ~

this causes the following on debian8:

[21:32:51] root:ifupdown2 # ifquery br0
auto br0
iface br0
	bridge-ports tap0 tap1

[21:32:53] root:ifupdown2 # ifreload -a
[21:32:56] root:ifupdown2 # ifreload -a
info: br0: reset bridge-hashel to default: 4096
info: br0: reset bridge-hashmax to default: 4096
info: reading '/sys/class/net/br0/bridge/stp_state'
info: br0: netlink: ip link set br0 type bridge with attributes
debug: br0: ifla_info_data {26: 4096, 27: 4096}
error: netlink: cannot set bridge br0 with options: Operation failed with 'Operation not supported'
[21:32:57] root:ifupdown2 #

because on the second ifreload, the bridge already exists so we check it's attribute to see if we have to reset to default. hashmax and hashel doesn't match with the default hardcoded in modinfo so we reset them, but apparently the netlink set isn't supported (that's another problem).
The thing here is that we shouldn't do anything for these attributes...
bridge-hashel 4096 and bridge-hashmax 4096 should be in Cumulus bridge policy files

Signed-off-by: Julien Fortin <julien@cumulusnetworks.com>