addons: vrf: dynamically add VRF valid range to modinfo dict
Ticket: CM-13693
Reviewed By: Roopa, Nikhil G, Daniel Walton, David K
Testing Done:

[8:13:45] root:~ # ifquery --syntax-help | grep "vrf-table" -A 6
  vrf-table
    help: vrf device routing table id. key to creating a vrf device. Table id is either 'auto' or 'valid routing table id'
    required: False
    validrange: 1001-1255
    validvals: auto,<number>
    example:
      vrf-table auto
      vrf-table 1001
  vrf
    help: vrf the interface is part of.
    required: False
    validvals: <text>
    example:
      vrf blue
[8:13:48] root:~ #

[8:23:22] root:~ # cat /var/lib/ifupdown2/policy.d/vrf.json
{
    "vrf": {
        "module_globals": {"vrf-table-id-start" : 1001,
                           "vrf-table-id-end" : 1255,
                           "vrf-max-count" : 64,
                           "vrf-mgmt-devname" : "mgmt",
                           "vrf-exec-cmd-prefix" : "/usr/bin/vrf task exec",
                           "vrf-helper" : "/usr/lib/vrf/vrf-helper",
                           "vrf-close-socks-on-down" : true}
	}
}
[8:27:52] root:~ #

[8:22:24] root:~ # ifquery --syntax-help | grep "vrf-table" -A 6
  vrf-table
    help: vrf device routing table id. key to creating a vrf device. Table id is either 'auto' or 'valid routing table id'
    required: False
    validrange: 1001-1255
    validvals: auto,<number>
    example:
      vrf-table auto
      vrf-table 1001
  vrf
    help: vrf the interface is part of.
    required: False
    validvals: <text>
    example:
      vrf blue

[8:22:30] root:~ # ifquery blue
auto blue
iface blue
	vrf-table 999

[8:22:32] root:~ # ifup -a --syntax-check
error: blue: vrf table id 999 out of reserved range [1001,1255]
[8:22:30] root:~ # ifquery blue
auto blue
iface blue
	vrf-table 1000

[8:22:58] root:~ # ifup -a --syntax-check
error: blue: vrf table id 1000 out of reserved range [1001,1255]
[8:23:04] root:~ # ifquery blue
auto blue
iface blue
	vrf-table 1001

[8:23:02] root:~ # ifup -a --syntax-check
[8:23:04] root:~ # ifquery blue
auto blue
iface blue
	vrf-table 1255

[8:23:09] root:~ # ifup -a --syntax-check
[8:23:04] root:~ # ifquery blue
auto blue
iface blue
	vrf-table 1256

[8:23:19] root:~ # ifup -a --syntax-check
error: blue: vrf table id 1256 out of reserved range [1001,1255]
[8:23:22] root:~ #