Improve installation on RHEL
What is the problem and potential resolutions (this commit picks last
one). Below is what I found and sent to Roopa.

Ifupdown2 on CL does not really "install" packages the python way
(since they do not reside under /usr/lib/python2.7/dist-packages which
is a Debian-python convention).

In case you do not belive me, try this:

	cd; python -c "import ifupdown"
	>Traceback (most recent call last):
	>File "<string>", line 1, in <module>
	>ImportError: No module named ifupdown

But how does ifupdown2 work? It relies on a the fact that if there is a file
'foo.py' in $PWD, it will load it first.
In case you do not belive me, try this:

	cd /usr/share/ifupdown2; python -c "import ifupdown"
	>#No import error

So, since /sbin/if{up,down,reload,query} tools are just symlinks to
/usr/share/ifupdown2/ifupdown2 executable,
everything is effectively running in /usr/share/ifupdown2

So what? It works on CL, doesn't it?  - Completely incidently, and addons
expose this problem on different OS's.

Here is how the problem manifests itself:

In addons.conf we load up ethool module that is "expected" to be found under
/usr/share/ifupdown2/addons/ethtool.py

This is done like so, check if file is there and use __import__ to load by name.

All is good, but on RHEL there is a file
/usr/lib64/python2.7/site-packages/ethtool.so and it loads this sucker up
instead (because its path is before, we did append for addon paths)

Snippet from pdb session:
(Pdb) sys.path
['/usr/share/ifupdown2/', '/usr/share/ifupdown2', '/usr/lib64/python27.zip',
'/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2',
'/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old',
'/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages',
'/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages',
'/usr/share/ifupdown2/addons']
(Pdb) mm = __import__('ethtool')
(Pdb) mm
<module 'ethtool' from '/usr/lib64/python2.7/site-packages/ethtool.so'>

On RHEL, there is a package python-ethtool that puts the file there.

So do does one suppose to do?

There are multiple ways around that:
- the most correct - get ifupdown packaging under control(this is a longer
  topic but well worth talking about)
- apppend to sys.path earlier (this is a bit hacky but will work)[Pick this one]