ifupdownaddons: modulebase: handle reserved vlans: fix range including reserved vlans
Ticket: CM-19075
Reviewed By: Roopa, Nikhil G
Testing Done: test from the bug, ifupdown2-tests

Un-caught regression: When a vlan (vlan 3010) or multiple vlans from
the default range is configured on a trunk, the switch gives an error
message - "error: swp20: reserved vlan 3010 being used (reserved vlan
range 3000-3999)". However, if a bigger range containing vlan/vlans
from the default range is configured on a trunk (for example 2999-4000),
the system does not provide an error message. When the config is comitted
all connections (bgp sessioins) with the fabrics are lost and it requires
to remove the config and restart the switchd.service.

root@H1:~# net add interface swp1 bridge vids 3000

root@H1:~# net commit
— /etc/network/interfaces	2018-01-31 18:53:32.659255304 +0000
+++ /var/run/nclu/iface/interfaces.tmp	2018-01-31 18:56:28.605267080 +0000
@@ -7,20 +7,20 @@

The primary network interface
auto eth0
iface eth0
address 192.168.0.15/24
gateway 192.168.0.2
ssim2 added
auto swp1
iface swp1

bridge-vids 1-200
+ bridge-vids 1-200 3000
link-autoneg off
link-duplex full
link-speed 10000
auto bridge
iface bridge
bridge-ports swp1

bridge-vids 1-200
+ bridge-vids 1-200 3000
bridge-vlan-aware yes
net add/del commands since the last 'net commit'
================================================

User Timestamp Command
---- -------------------------- ---------------------------------------
root 2018-01-31 18:56:25.540640 net add interface swp1 bridge vids 3000
root 2018-01-31 18:56:28.605315 net commit

ERROR: '/sbin/ifreload -a' failed due to:
error: swp1: swp1: reserved vlan 3000 being used (reserved vlan range 3000-3999)
error: swp1: reserved vlan 3000 being used (reserved vlan range 3000-3999)
Command '['/sbin/ifreload', '-a']' returned non-zero exit status 1

ERROR: 'net commit' failed for iface, all changes will remain in 'net pending'
root@H1:~# net pending
— /etc/network/interfaces	2018-01-31 18:56:28.785267000 +0000
+++ /var/run/nclu/iface/interfaces.tmp	2018-01-31 18:56:52.613268687 +0000
@@ -7,20 +7,20 @@

The primary network interface
auto eth0
iface eth0
address 192.168.0.15/24
gateway 192.168.0.2
ssim2 added
auto swp1
iface swp1

bridge-vids 1-200
+ bridge-vids 1-200 3000
link-autoneg off
link-duplex full
link-speed 10000
auto bridge
iface bridge
bridge-ports swp1

bridge-vids 1-200
+ bridge-vids 1-200 3000
bridge-vlan-aware yes
net add/del commands since the last 'net commit'
================================================

User Timestamp Command
---- -------------------------- ---------------------------------------
root 2018-01-31 18:56:25.540640 net add interface swp1 bridge vids 3000
root 2018-01-31 18:56:28.605315 net commit
root@H1:~#
root@H1:~#

root@H1:~# net add interface swp1 bridge vids 2800-3010

root@H1:~# net commit
— /etc/network/interfaces	2018-01-31 18:57:23.540270000 +0000
+++ /var/run/nclu/iface/interfaces.tmp	2018-01-31 18:58:03.907273459 +0000
@@ -7,20 +7,20 @@

The primary network interface
auto eth0
iface eth0
address 192.168.0.15/24
gateway 192.168.0.2
ssim2 added
auto swp1
iface swp1

bridge-vids 1-200
+ bridge-vids 1-200 2800-3010
link-autoneg off
link-duplex full
link-speed 10000
auto bridge
iface bridge
bridge-ports swp1

bridge-vids 1-200
+ bridge-vids 1-200 2800-3010
bridge-vlan-aware yes
net add/del commands since the last 'net commit'
================================================

User Timestamp Command
---- -------------------------- --------------------------------------------
root 2018-01-31 18:58:01.450483 net add interface swp1 bridge vids 2800-3010
root 2018-01-31 18:58:03.908093 net commit

root@H1:~# echo $?
0
root@H1:~# cat /etc/networ
network/ networks
root@H1:~# cat /etc/network/
if-post-down.d/ if-pre-up.d/ if-up.d/ ifupdown2/ interfaces interfaces.d/ run/
root@H1:~# cat /etc/network/interf
interfaces interfaces.d/
root@H1:~# cat /etc/network/interfaces

This file describes the network interfaces available on your system
and how to activate them. For more information, see interfaces(5).
source /etc/network/interfaces.d/*.intf
The loopback network interface
auto lo
iface lo inet loopback
The primary network interface
auto eth0
iface eth0
address 192.168.0.15/24
gateway 192.168.0.2
ssim2 added
auto swp1
iface swp1
bridge-vids 1-200 2800-3010
link-autoneg off
link-duplex full
link-speed 10000

auto bridge
iface bridge
bridge-ports swp1
bridge-vids 1-200 2800-3010
bridge-vlan-aware yes
root@H1:~#
root@H1:~#
root@H1:~# exit

Signed-off-by: Julien Fortin <julien@cumulusnetworks.com>