diff: add lower dev of removed interfaces to the run queue
$ cat $BEFORE

[...]

auto hostbond_4
iface hostbond_4
        mtu 9100
        bond-slaves swp8
        bond-mode 802.3ad
        bond-lacp-bypass-allow yes
        bridge-pvid 1002

auto swp8
iface swp8
link-speed 10000
    link-autoneg off

auto br_default
iface br_default
    bridge-ports swp5 hostbond_4
    hwaddress 44:38:39:ff:ff:13
    bridge-vlan-aware yes
    bridge-vids 1000 1002 1004 1006 1008
    bridge-pvid 1
    bridge-stp yes
    bridge-mcsnoop no
    mstpctl-forcevers rstp
$
$
$
$ cat $AFTER

[...]

auto swp8
iface swp8
link-speed 10000
    link-autoneg off

auto swp8.4000
iface swp8.4000
    vrf vrf1

auto vrf1
iface vrf1
      vrf-table auto

auto br_default
iface br_default
    bridge-ports swp5
    hwaddress 44:38:39:ff:ff:13
    bridge-vlan-aware yes
    bridge-vids 1000 1002 1004 1006 1008
    bridge-pvid 1
    bridge-stp yes
    bridge-mcsnoop no
    mstpctl-forcevers rstp
$
$ ifdown -a -X eth0 -X mgmt ; cp $BEFORE /etc/network/interfaces ; ifreload -a ; cp $AFTER /etc/network/interfaces ; ifreload -a --diff;
error: swp8.4000: netlink: swp8.4000: ip link set dev swp8.4000 up: operation failed with 'Network is down' (100)
$

In that case swp8 goes down when hostbond_4 is removed, swp8 /e/n/i config hasn't changed though, so it's not picked up by --diff
therefore its not reloaded and stays down which is a problem.

The fix is to add lower devices of removed interfaces to the run queue.

Signed-off-by: Julien Fortin <jfortin@nvidia.com>