ifquery/ifup/ifdown: filter interfaces list when allow class is defined.
Currently, when ifquery list/ifup/idown is used with allow=class + ifaces list,

ifupdown2 is merging list of all interfaces of the class + the ifaces list.

ifupdown1 behaviour is to filter the ifaces list with only the allowed class.

Also current ifupdown2 man page :"--allow CLASS ignore non-"allow-CLASS" interfaces"

```
/etc/network/interfaces

allow-hotplug eth0
auto eth0
iface eth0

auto eth1
iface eth1
```

Current:

```
ifquery -l --allow=hotplug eth0 eth1

eth0
eth0
eth1

ifup --allow=hotplug eth1 -d

debug: scheduling '['pre-up', 'up', 'post-up']' for ['eth0', 'eth1']

```

After this patch, like ifupdown1:

```
ifquery -l --allow=hotplug eth0 eth1

eth0

ifup --allow=hotplug eth1 -d

error: main exception: no ifaces found matching given allow lists

```

Fixes #206