addons: vrf: syntax check for vrf-table id
Ticket: CM-13693
Reviewed By: Roopa, Julien
Testing Done: nclu command mentioned in the bug

Adding syntax check for vrf-table id

$ net add vrf red vrf-table 16
$ net pending
--- /etc/network/interfaces 2017-04-12 20:22:05.913544861 +0000
+++ /var/run/nclu/iface/interfaces.tmp  2017-04-12 20:33:35.192862644 +0000
@@ -24,10 +24,14 @@
 iface peerlink-3.4094
     address 169.254.0.10/30
          mtu 9202
          alias clag and vxlan communication primary path
     clagd-priority 8192
     clagd-sys-mac 44:38:39:ff:ff:01
     clagd-peer-ip 169.254.0.9
     clagd-args --vm
     #post-up sysctl -w net.ipv4.conf.peerlink-3/4094.accept_local=1
     clagd-backup-ip 27.0.0.11
+
+auto red
+iface red
+    vrf-table 16

ERROR: pending changes will introduce the following errors in /etc/network/interfaces

warning: red: vrf table id 16 out of reserved range [1001,1255]

net add/del commands since the last 'net commit'
================================================

User    Timestamp                   Command
------  --------------------------  ----------------------------
root    2017-04-12 20:33:21.477030  net add vrf red vrf-table 16
$
$
$
$ net commit
--- /etc/network/interfaces 2017-04-12 20:22:05.913544861 +0000
+++ /var/run/nclu/iface/interfaces.tmp  2017-04-12 20:34:18.043830664 +0000
@@ -24,10 +24,14 @@
 iface peerlink-3.4094
     address 169.254.0.10/30
          mtu 9202
          alias clag and vxlan communication primary path
     clagd-priority 8192
     clagd-sys-mac 44:38:39:ff:ff:01
     clagd-peer-ip 169.254.0.9
     clagd-args --vm
     #post-up sysctl -w net.ipv4.conf.peerlink-3/4094.accept_local=1
     clagd-backup-ip 27.0.0.11
+
+auto red
+iface red
+    vrf-table 16

net add/del commands since the last 'net commit'
================================================

User    Timestamp                   Command
------  --------------------------  ----------------------------
root    2017-04-12 20:33:21.477030  net add vrf red vrf-table 16
root    2017-04-12 20:34:18.043553  net commit

ERROR: We cannot commit the current pending changes due to the following errors
they would introduce in /etc/network/interfaces:

warning: red: vrf table id 16 out of reserved range [1001,1255]

ERROR: 'net commit' failed for iface, all changes will remain in 'net pending'

Signed-off-by: Nikhil Gajendrakumar <nikhil@cumulusnetworks.com>