addons: vlan: raw-device: check if cache value is valid before more checks
Ticket: CM-21841

last vlan-raw-device introduced a bug in some scenario:
error: swp1.4: cannot change vlan-raw-device from swp1 to None: operation not supported.
Please delete the device with 'ifdown swp1.4' and recreate it to apply the change.

this extra check fixes the issue

Signed-off-by: Julien Fortin <julien@cumulusnetworks.com>